### ISSUE TITLE
Members not publicly visible

### ISSUE THREAD

**Issue by PLNReynolds** [ucdavisdatalab/research-toolkits#3]
@ctb discovered that members of the org aren't visible (to reproduce, view 'people' in incognito mode). @avkoehl can you please look into this org level issue?

**Comment by ctb** [comment]
On Wed, Jan 27, 2021 at 01:53:48PM -0800, PLNReynolds wrote:
> @ctb discovered that members of the org aren't visible (to reproduce, view 'people' in incognito mode). @avkoehl can you please look into this org level issue?

this is straightforward to fix by going to your member entry and setting
it to 'public' - I just set it that way for myself.

You can do this on https://github.com/orgs/ucdavisdatalab/people

I do not know if this can be set to public by default, nor (imo) should
it be - but I think it'd be nice to have a few people on there that are
public.

best,
--titus

**Comment by avkoehl** [comment]
Skimmed some docs, don't see a clear way of setting membership visibility by default. Did find out how to do it for github enterprise though https://docs.github.com/en/enterprise-server@2.20/admin/user-management/configuring-visibility-for-organization-membership. 

Here is documentation for what Titus mentioned. https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership. Note a side effect will be that the organizations will be visible from your profile to the public.

I went ahead and made myself visible as well

**Comment by avkoehl** [comment]
Somewhat an aside. @PLNReynolds use the assignees option on the issue itself. Makes it more likely I will notice that I need to do something. And makes it clearer who is ultimately responsible for the task being resolved.

I think we can close this?

**Comment by ctb** [comment]
👍

**Comment by PLNReynolds** [comment]
Thanks @avkoehl - I tried to assign you initially but you weren't showing up as available (but now that you've commented on an issue I can see you - weird GitHub quirk or my user error?). I like suggestion for people to opt-in to being  public. Will bring it up at standup.

**Comment by avkoehl** [comment]
> Thanks @avkoehl - I tried to assign you initially but you weren't showing up as available (but now that you've commented on an issue I can see you - weird GitHub quirk or my user error?). I like suggestion for people to opt-in to being public. Will bring it up at standup.

Did you try searching for me? It could be that I wasnt in the suggested list, but manually searching for me would have done the trick.
